version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
